### ISSUE TITLE
你那一堆ss的节点怎么来的

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#255]
### 详细说明

```bash
你那一堆ss/ssr的节点怎么来的，是在url里注入到pool池子里的吧
```

**Comment by anjue39** [comment]
```
on: 
  repository_dispatch: #https://www.chenshaowen.com/blog/how-to-trigger-github-action-remotely.html
    types:
      - Webhook
  # schedule: #UTC+0               #UTC+8
  #   - cron: '*/35 0-8 * * 1-5'   #工作日 上午8:00 - 下午4:00
  #   - cron: '*/25 8-14 * * 1-5'  #工作日 下午4:00 - 晚上10:00
  #   - cron: '*/55 14-21 * * 1-4' #工作日 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 21-23 * * 1-5' #工作日 次日凌晨5:00 - 次日上午8:00
  #   - cron: '*/25 14-21 * * 5'   #星期五 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 * * * 0,6'     #休息日 全天候
  workflow_dispatch: #手动调试按钮
```
你现在不是自动生产了？但是我看你间隔也很规律频繁，纯手动调试貌似不像
